import array as arr

angka = arr.array('i', [1,2,3])

print('')
print('===========================')
print('     Original Array    ')
print('===========================')
print(angka)
print('')
print('==========================================')
print('     Append = Add Item to End of Index')
print('==========================================')
angka.append(4)
angka.append(5)
print(angka)
print('')
print('==============================================')
print(' EXTEND = ADD MORE ITEMS TO THE END OF INDEX')
print('==============================================')
angka.extend([6,7,8, 9, 10])

print(angka)
print('')
print('==============================================')
print(' INSERT = ADD ITEMS WITH INDEX OF POSITION')
print('==============================================')
angka.insert(0,0)
angka.insert(11,20)
print(angka)
print('')
print('==============================================')
print(' REMOVE = DELETE ITEMS BY VALUE')
print('==============================================')
angka.remove(20)
print(angka)
print('')
print('==============================================')
print(' POP = DELETE ITEMS BY INDEX')
print('==============================================')
angka.remove(0)
print(angka)
print('')



